---
title: "A Shiny app for exploring iGraph networks"
author: "Phu T. Van"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
runtime: shiny
output:
  BiocStyle::html_document:
  toc: yes
---
  
  
```{r overall-knitr-options, cache=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
library(knitr)
opts_chunk$set(cache=TRUE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results='asis')

library(Biobase)
library(data.table)
library(ggplot2)
library(gridExtra)
library(limma)
library(edgeR)
library(DESeq2)
library(xtable)
library(GSEABase)
library(DT)
library(plyr)     ## join
library(stringr)  ## str_trim
library(shiny)
library(igraph)
library(ggnetwork)

```

```{r network}
   n <- make_STRING_igraph(DEGout[[1]], string_db)



```

```{r shiny, echo=FALSE, cache=FALSE}

 
   shinyApp(
    shinyUI(fluidPage(
  
      # Application title
      titlePanel("iGraph network"),
      
      sidebarLayout(
        sidebarPanel(
         
          selectInput("select", "Choose data set",
                      colnames(rot)[(len-6):len])
          ),
      
        mainPanel(
            ##DT::dataTableOutput("view"),
            plotOutput("netPlot")
        )
    ))),
    
    shinyServer(function(input, output) {
      selectedData <- reactive({input$select})
     
       output$netPlot <- renderPlot({
           ggplot(ggnetwork(n, layout="adj"), aes(x=x,y=y,xend=xend,yend=yend)) +
            geom_edges(aes(linetype = "1"), color = "grey50") +
            geom_nodes(color="grey90", size=10) +
            geom_nodetext(aes(label=geneName)) +
            theme_blank()
      }) ## end renderPlot
       
    }) ## end shinyServer

) ## end shinyApp

   
   
```





